import { test, describe } from 'node:test';
import { strict as assert } from 'node:assert';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { composeRules } from '../../cli/src/composer.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const niyamRoot = path.resolve(__dirname, '../../');

describe('composeRules', () => {
  test('composes single stack', () => {
    const config = { stacks: ['react'] };
    const result = composeRules(config, niyamRoot);
    assert.ok(typeof result === 'string');
    assert.ok(result.length > 0);
    assert.ok(result.includes('Tech Stack'), 'Expected Tech Stack section');
  });

  test('adds header with Generated by Niyam', () => {
    const config = { stacks: ['typescript'] };
    const result = composeRules(config, niyamRoot);
    assert.ok(result.includes('Generated by Niyam'), 'Expected header to contain "Generated by Niyam"');
  });

  test('handles missing rules gracefully', () => {
    const config = { stacks: ['nonexistent-stack-xyz'] };
    const result = composeRules(config, niyamRoot);
    assert.ok(typeof result === 'string');
    assert.ok(result.includes('Generated by Niyam'), 'Should still produce valid output');
  });
});
