export interface Rule {
  id: string;
  name: string;
  description: string;
  category: "stacks" | "roles" | "principles" | "workflows" | "anti-patterns" | "languages";
  tags: string[];
}

export const rules: Rule[] = [
  // === Stacks (23) ===
  {
    id: "react",
    name: "React",
    description: "Rules for React 19+ with hooks, Server Components, performance patterns, and accessibility",
    category: "stacks",
    tags: ["frontend", "ui", "components", "hooks", "javascript", "typescript"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    description: "Rules for Next.js 15+ App Router with Server Components, Server Actions, and caching strategies",
    category: "stacks",
    tags: ["frontend", "fullstack", "ssr", "react", "framework"],
  },
  {
    id: "python",
    name: "Python",
    description: "Rules for Python 3.12+ with type hints, async, modern packaging, and pytest",
    category: "stacks",
    tags: ["backend", "scripting", "data", "async", "typing"],
  },
  {
    id: "go",
    name: "Go",
    description: "Rules for Go 1.22+ with error handling, interfaces, concurrency, and table-driven tests",
    category: "stacks",
    tags: ["backend", "systems", "concurrency", "microservices", "cli"],
  },
  {
    id: "rust",
    name: "Rust",
    description: "Rules for Rust with ownership, error handling, async Tokio, traits, and cargo conventions",
    category: "stacks",
    tags: ["systems", "backend", "performance", "safety", "async"],
  },
  {
    id: "flutter",
    name: "Flutter",
    description: "Rules for Flutter 3+ with widget composition, Riverpod/Bloc state management, and go_router",
    category: "stacks",
    tags: ["mobile", "cross-platform", "dart", "ui", "ios", "android"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    description: "Rules for TypeScript 5+ with strict mode, generics, discriminated unions, and branded types",
    category: "stacks",
    tags: ["language", "typing", "frontend", "backend", "fullstack"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    description: "Rules for Tailwind CSS 4+ with utility-first patterns, design tokens, and responsive design",
    category: "stacks",
    tags: ["css", "styling", "frontend", "design-system", "utility-first"],
  },
  {
    id: "node",
    name: "Node.js",
    description: "Rules for Node.js 22+ with ESM, streams, worker threads, and security best practices",
    category: "stacks",
    tags: ["backend", "runtime", "javascript", "api", "server"],
  },
  {
    id: "svelte",
    name: "Svelte",
    description: "Rules for Svelte 5+ with runes, SvelteKit, load functions, and form actions",
    category: "stacks",
    tags: ["frontend", "ui", "framework", "ssr", "compiler"],
  },
  {
    id: "vue",
    name: "Vue",
    description: "Rules for Vue 3+ with Composition API, Pinia stores, composables, and Nuxt 3",
    category: "stacks",
    tags: ["frontend", "ui", "framework", "composition-api", "typescript"],
  },
  {
    id: "django",
    name: "Django",
    description: "Rules for Django 5+ with ORM best practices, DRF, Celery, and security",
    category: "stacks",
    tags: ["backend", "python", "orm", "rest-api", "fullstack"],
  },
  {
    id: "fastapi",
    name: "FastAPI",
    description: "Rules for FastAPI with async routes, Pydantic v2, dependency injection, and WebSocket",
    category: "stacks",
    tags: ["backend", "python", "async", "rest-api", "pydantic"],
  },
  {
    id: "angular",
    name: "Angular",
    description: "Rules for Angular 18+ with signals, standalone components, new control flow, and NgRx",
    category: "stacks",
    tags: ["frontend", "framework", "typescript", "spa", "enterprise"],
  },
  {
    id: "laravel",
    name: "Laravel",
    description: "Rules for Laravel 11+ with Eloquent, Blade components, queues, events, and Pest testing",
    category: "stacks",
    tags: ["backend", "php", "fullstack", "orm", "framework"],
  },
  {
    id: "remix",
    name: "Remix",
    description: "Rules for Remix 2+ with loaders, actions, nested routes, error boundaries, streaming, and progressive enhancement",
    category: "stacks",
    tags: ["fullstack", "react", "ssr", "framework", "web-standards"],
  },
  {
    id: "prisma",
    name: "Prisma",
    description: "Rules for Prisma ORM with schema design, relations, transactions, raw queries, migrations, and seeding",
    category: "stacks",
    tags: ["orm", "database", "backend", "typescript", "migrations"],
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Rules for Supabase with Auth, RLS policies, realtime subscriptions, edge functions, storage, and database types",
    category: "stacks",
    tags: ["backend", "database", "auth", "realtime", "baas", "postgres"],
  },
  {
    id: "docker",
    name: "Docker",
    description: "Rules for Docker with multi-stage builds, layer caching, .dockerignore, compose, health checks, and security scanning",
    category: "stacks",
    tags: ["devops", "containers", "infrastructure", "deployment", "ci-cd"],
  },
  {
    id: "aws",
    name: "AWS",
    description: "Rules for AWS with Lambda, DynamoDB, S3, CDK/Terraform, IAM least privilege, CloudWatch, and cost optimization",
    category: "stacks",
    tags: ["cloud", "infrastructure", "serverless", "devops", "iaas"],
  },
  {
    id: "shadcn",
    name: "shadcn/ui",
    description: "Rules for shadcn/ui with component installation, customization, theming, accessibility, compound components, and variants",
    category: "stacks",
    tags: ["ui", "components", "frontend", "design-system", "radix", "tailwind"],
  },
  {
    id: "drizzle",
    name: "Drizzle ORM",
    description: "Rules for Drizzle ORM with schema definition, queries, relations, migrations, type safety, and transactions",
    category: "stacks",
    tags: ["orm", "database", "backend", "typescript", "sql"],
  },
  {
    id: "astro",
    name: "Astro",
    description: "Rules for Astro 5+ with content collections, islands architecture, view transitions, SSR/SSG, and integrations",
    category: "stacks",
    tags: ["frontend", "ssg", "ssr", "framework", "content", "islands"],
  },

  // === Roles (12) ===
  {
    id: "backend",
    name: "Backend Developer",
    description: "Designs and builds scalable, secure server-side systems with optimized APIs and data management",
    category: "roles",
    tags: ["backend", "api", "database", "auth", "caching", "microservices", "rest", "graphql"],
  },
  {
    id: "frontend",
    name: "Frontend Developer",
    description: "Builds performant, accessible, and responsive user interfaces with component-driven architecture",
    category: "roles",
    tags: ["frontend", "accessibility", "performance", "components", "css", "responsive", "wcag", "core-web-vitals"],
  },
  {
    id: "fullstack",
    name: "Full-Stack Developer",
    description: "Delivers end-to-end features with unified API contracts, shared types, and seamless frontend-backend integration",
    category: "roles",
    tags: ["fullstack", "api-contracts", "monorepo", "ssr", "websocket", "migrations", "deployment", "shared-types"],
  },
  {
    id: "devops",
    name: "DevOps Engineer",
    description: "Builds reliable CI/CD pipelines, infrastructure as code, and observability systems for production excellence",
    category: "roles",
    tags: ["devops", "ci-cd", "kubernetes", "docker", "terraform", "monitoring", "infrastructure", "deployment"],
  },
  {
    id: "mobile",
    name: "Mobile Developer",
    description: "Builds cross-platform mobile apps with offline-first architecture, native performance, and platform compliance",
    category: "roles",
    tags: ["mobile", "react-native", "flutter", "offline-first", "ios", "android", "push-notifications", "deep-linking"],
  },
  {
    id: "security",
    name: "Security Engineer",
    description: "Identifies and mitigates security vulnerabilities through threat modeling, secure coding, and defense-in-depth",
    category: "roles",
    tags: ["security", "owasp", "encryption", "auth", "threat-modeling", "csp", "cors", "audit"],
  },
  {
    id: "data",
    name: "Data Engineer",
    description: "Designs and builds reliable data pipelines, models, and governance systems for analytics and decision-making",
    category: "roles",
    tags: ["data", "etl", "sql", "pipeline", "data-quality", "dbt", "airflow", "data-modeling"],
  },
  {
    id: "ui-ux",
    name: "UI/UX Developer",
    description: "Implements design systems, interaction patterns, and polished user experiences from design to production",
    category: "roles",
    tags: ["ui", "ux", "design-system", "design-tokens", "components", "figma", "interactions", "responsive"],
  },
  {
    id: "qa-tester",
    name: "QA/Test Engineer",
    description: "Designs test strategies, writes automation frameworks, catches edge cases, and ensures software quality through systematic verification",
    category: "roles",
    tags: ["testing", "qa", "automation", "regression", "load-testing", "edge-cases", "bug-reports", "ci"],
  },
  {
    id: "technical-writer",
    name: "Technical Writer",
    description: "Creates clear API documentation, tutorials, changelogs, READMEs, and architecture decision records that developers actually read",
    category: "roles",
    tags: ["documentation", "api-docs", "tutorials", "changelog", "readme", "jsdoc", "tsdoc", "adr"],
  },
  {
    id: "architect",
    name: "Software Architect",
    description: "Designs scalable systems, manages technical trade-offs, documents decisions in ADRs, and guides teams through complexity",
    category: "roles",
    tags: ["architecture", "system-design", "scalability", "trade-offs", "tech-debt", "adr", "design-patterns", "distributed-systems"],
  },
  {
    id: "ai-engineer",
    name: "AI/ML Engineer",
    description: "Integrates AI models, designs RAG pipelines, engineers prompts, evaluates outputs, and optimizes cost while maintaining safety guardrails",
    category: "roles",
    tags: ["ai", "ml", "llm", "rag", "embeddings", "prompt-engineering", "fine-tuning", "evaluation", "guardrails"],
  },

  // === Principles (6) ===
  {
    id: "clean-code",
    name: "Clean Code",
    description: "Robert C. Martin's clean code principles adapted as actionable directives for AI agents",
    category: "principles",
    tags: ["clean-code", "naming", "functions", "formatting", "solid", "readability"],
  },
  {
    id: "tdd",
    name: "Test-Driven Development",
    description: "Kent Beck's TDD principles: Red-Green-Refactor cycle adapted for AI-driven development",
    category: "principles",
    tags: ["tdd", "testing", "red-green-refactor", "test-first", "design"],
  },
  {
    id: "ddd",
    name: "Domain-Driven Design",
    description: "Eric Evans' DDD principles: bounded contexts, aggregates, and ubiquitous language for complex domains",
    category: "principles",
    tags: ["ddd", "domain-driven-design", "bounded-context", "aggregates", "architecture"],
  },
  {
    id: "security-first",
    name: "Security First",
    description: "OWASP and Zero Trust security principles: validate everything, trust nothing, defend in depth",
    category: "principles",
    tags: ["security", "owasp", "zero-trust", "authentication", "authorization", "input-validation"],
  },
  {
    id: "performance",
    name: "Performance",
    description: "Brendan Gregg's methodology and Core Web Vitals: measure, profile, optimize the bottleneck",
    category: "principles",
    tags: ["performance", "core-web-vitals", "profiling", "caching", "optimization"],
  },
  {
    id: "accessibility",
    name: "Accessibility",
    description: "WCAG 2.2 AA compliance: semantic HTML, ARIA, keyboard navigation, and inclusive design",
    category: "principles",
    tags: ["accessibility", "a11y", "wcag", "aria", "keyboard-navigation", "screen-reader"],
  },

  // === Workflows (5) ===
  {
    id: "git",
    name: "Git Workflow",
    description: "Conventional commits, branch naming, PR discipline, and automation hooks for clean history",
    category: "workflows",
    tags: ["git", "version-control", "conventional-commits", "branching", "pull-requests"],
  },
  {
    id: "ci-cd",
    name: "CI/CD Pipeline",
    description: "Pipeline stages, caching, parallel jobs, environment promotion, and deployment gates",
    category: "workflows",
    tags: ["ci-cd", "pipeline", "deployment", "automation", "continuous-integration"],
  },
  {
    id: "testing",
    name: "Testing Strategy",
    description: "Test pyramid, isolation, fixtures, factories, and flaky test prevention for reliable suites",
    category: "workflows",
    tags: ["testing", "test-pyramid", "unit-tests", "integration", "e2e", "test-isolation"],
  },
  {
    id: "deployment",
    name: "Deployment",
    description: "Blue-green, canary, feature flags, zero-downtime deployments, and incident response",
    category: "workflows",
    tags: ["deployment", "blue-green", "canary", "feature-flags", "zero-downtime", "rollback"],
  },
  {
    id: "code-review",
    name: "Code Review",
    description: "Review checklist, feedback style, PR discipline, and automated quality gates",
    category: "workflows",
    tags: ["code-review", "pull-requests", "feedback", "quality", "collaboration"],
  },

  // === Anti-Patterns (2) ===
  {
    id: "common",
    name: "Common Anti-Patterns",
    description: "Universal code anti-patterns to detect and avoid: over-engineering, premature optimization, god objects, callback hell, magic numbers, and stringly-typed code",
    category: "anti-patterns",
    tags: ["anti-patterns", "code-smells", "refactoring", "clean-code", "design", "universal"],
  },
  {
    id: "ai-slop",
    name: "AI-Generated Code Anti-Patterns",
    description: "Anti-patterns specific to AI-generated code: zombie comments, swallowed exceptions, as-any casts, dead imports, over-abstraction, hallucinated APIs, and copy-paste patterns",
    category: "anti-patterns",
    tags: ["anti-patterns", "ai-slop", "llm", "code-quality", "code-review", "ai-generated"],
  },

  // === Languages (2) ===
  {
    id: "javascript",
    name: "JavaScript",
    description: "JavaScript-specific rules: closures, prototypes, event loop, WeakRef, async patterns, module systems, and runtime gotchas",
    category: "languages",
    tags: ["javascript", "js", "closures", "async", "event-loop", "modules", "es2024", "runtime"],
  },
  {
    id: "sql",
    name: "SQL",
    description: "SQL rules: query optimization, indexing strategies, joins, CTEs, window functions, transactions, and migration best practices",
    category: "languages",
    tags: ["sql", "database", "queries", "indexing", "optimization", "migrations", "postgres", "mysql"],
  },
];

export const categories = [
  { key: "all", label: "All", count: 50 },
  { key: "stacks", label: "Stacks", count: 23 },
  { key: "roles", label: "Roles", count: 12 },
  { key: "principles", label: "Principles", count: 6 },
  { key: "workflows", label: "Workflows", count: 5 },
  { key: "anti-patterns", label: "Anti-patterns", count: 2 },
  { key: "languages", label: "Languages", count: 2 },
] as const;
