import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const DEFAULT_NIYAM_ROOT = resolve(__dirname, '..', '..');

const VERSION = 'v0.1.0';
const CATEGORIES = ['stacks', 'roles', 'principles', 'workflows'];

export function composeRules(config, niyamRoot) {
  const stacks = config.stacks || [];
  const roles = config.roles || [];
  const principles = config.principles || [];
  const workflows = config.workflows || [];

  const allModules = [...principles, ...stacks, ...roles, ...workflows];
  const lines = [];

  // Header
  lines.push(`<!-- Generated by Niyam ${VERSION} -->`);
  lines.push(`<!-- Modules: ${allModules.join(', ')} -->`);
  lines.push(`<!-- Regenerate: npx niyam generate -->`);
  lines.push('');
  lines.push('# Project Rules (Niyam)');
  lines.push('');

  // Active Modules summary
  lines.push('## Active Modules');
  if (stacks.length) lines.push(`- Stacks: ${stacks.join(', ')}`);
  if (roles.length) lines.push(`- Roles: ${roles.join(', ')}`);
  if (principles.length) lines.push(`- Principles: ${principles.join(', ')}`);
  if (workflows.length) lines.push(`- Workflows: ${workflows.join(', ')}`);
  lines.push('');

  // Principles
  if (principles.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Principles');
    lines.push('');
    for (const name of principles) {
      const content = loadRule(niyamRoot, 'principles', name);
      if (content) {
        lines.push(content);
        lines.push('');
      }
    }
  }

  // Tech Stack
  if (stacks.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Tech Stack');
    lines.push('');
    for (const name of stacks) {
      const content = loadRule(niyamRoot, 'stacks', name);
      if (content) {
        lines.push(content);
        lines.push('');
      }
    }
  }

  // Role Guidelines
  if (roles.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Role Guidelines');
    lines.push('');
    for (const name of roles) {
      const content = loadRule(niyamRoot, 'roles', name);
      if (content) {
        lines.push(content);
        lines.push('');
      }
    }
  }

  // Workflows
  if (workflows.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Workflows');
    lines.push('');
    for (const name of workflows) {
      const content = loadRule(niyamRoot, 'workflows', name);
      if (content) {
        lines.push(content);
        lines.push('');
      }
    }
  }

  // Footer with line count
  lines.push('---');
  lines.push('');
  const lineCount = lines.length + 1; // +1 for the footer line itself
  lines.push(`<!-- ${lineCount} lines | Niyam ${VERSION} -->`);

  return lines.join('\n');
}

function loadRule(root, category, name) {
  const filePath = join(root, category, name, 'rules.md');
  if (!existsSync(filePath)) return null;
  try {
    return readFileSync(filePath, 'utf8').trim();
  } catch {
    return null;
  }
}

export function getAvailableRules(niyamRoot) {
  const available = {};

  for (const category of CATEGORIES) {
    available[category] = [];
    const categoryDir = join(niyamRoot, category);
    if (!existsSync(categoryDir)) continue;

    try {
      const entries = readdirSync(categoryDir, { withFileTypes: true });
      for (const entry of entries) {
        if (!entry.isDirectory()) continue;
        const metaPath = join(categoryDir, entry.name, 'meta.json');
        if (existsSync(metaPath)) {
          try {
            const meta = JSON.parse(readFileSync(metaPath, 'utf8'));
            available[category].push({ id: entry.name, name: meta.name || entry.name });
          } catch {
            available[category].push({ id: entry.name, name: entry.name });
          }
        } else {
          available[category].push({ id: entry.name, name: entry.name });
        }
      }
    } catch {
      // category directory unreadable, skip
    }
  }

  return available;
}


export function loadMeta(category, id, niyamRoot = DEFAULT_NIYAM_ROOT) {
  const metaPath = join(niyamRoot, category, id, 'meta.json');
  if (!existsSync(metaPath)) return null;
  try {
    return JSON.parse(readFileSync(metaPath, 'utf8'));
  } catch {
    return null;
  }
}

export function searchRules(query, niyamRoot = DEFAULT_NIYAM_ROOT) {
  const results = [];
  const lowerQuery = query.toLowerCase();

  for (const category of CATEGORIES) {
    const categoryDir = join(niyamRoot, category);
    if (!existsSync(categoryDir)) continue;

    let entries;
    try {
      entries = readdirSync(categoryDir, { withFileTypes: true });
    } catch {
      continue;
    }

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      const meta = loadMeta(category, entry.name, niyamRoot);
      const name = meta?.name || entry.name;
      const description = meta?.description || '';

      // Check if name or description matches
      const nameMatch = name.toLowerCase().includes(lowerQuery);
      const descMatch = description.toLowerCase().includes(lowerQuery);

      // Check rule content for matches
      const rulesPath = join(categoryDir, entry.name, 'rules.md');
      const matches = [];
      if (existsSync(rulesPath)) {
        try {
          const content = readFileSync(rulesPath, 'utf8');
          const lines = content.split('\n');
          for (const line of lines) {
            if (line.toLowerCase().includes(lowerQuery)) {
              matches.push(line.trim());
            }
          }
        } catch {
          // skip unreadable files
        }
      }

      if (nameMatch || descMatch || matches.length > 0) {
        results.push({ category, id: entry.name, name, description, matches });
      }
    }
  }

  return results;
}
